string(APPEND CPPDEFS " -DHAVE_GETTID")

if (COMP_WAV STREQUAL ww3)
  if (MPILIB STREQUAL openmpi)
     string(APPEND SLIBS "  -l:libparmetis.a -lmetis ")
  endif()
endif()

set(NETCDF_C_PATH	$ENV{EBROOTNETCDF})
set(NETCDF_FORTRAN_PATH $ENV{EBROOTNETCDFMINFORTRAN})
set(PNETCDF_PATH	$ENV{EBROOTPNETCDF})
set(PIO_FILESYSTEM_HINTS "lustre")

if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_NANOTIME -DBIT64 -DHAVE_VPRINTF -DHAVE_BACKTRACE -DHAVE_SLASHPROC -DHAVE_COMM_F2C -DHAVE_TIMES -DHAVE_GETTIMEOFDAY")
endif()